export const CREATE_CHAT_ROOM = 'CREATE_CHAT_ROOM';
export const GET_ALL_ROOMS = 'GET_ALL_ROOMS';
export const SET_ALL_ROOMS = 'SET_ALL_ROOMS';
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const GET_CURRENT_CHAT_ROOM = 'GET_CURRENT_CHAT_ROOM';
export const DELETE_CHAT_ROOM = 'DELETE_CHAT_ROOM';
export const UPDATE_ROOMS_CREATED = 'UPDATE_ROOMS_CREATED';

export const CREATE_CHAT_ROOM_PENDING = 'CREATE_CHAT_ROOM_PENDING';
export const GET_ALL_ROOMS_PENDING = 'GET_ALL_ROOMS_PENDING';
export const GET_CHAT_ROOM_PENDING = 'GET_CHAT_ROOM_PENDING';
export const DELETE_CHAT_ROOM_PENDING = 'DELETE_CHAT_ROOM_PENDING';
export const GET_CURRENT_CHAT_ROOM_PENDING = 'GET_CURRENT_CHAT_ROOM_PENDING';

export const CHATROOM_API_ERROR = 'CHATROOM_API_ERROR';