# Generated by Django 3.2.4 on 2021-07-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_auto_20210705_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_on']},
        ),
    ]
